package me.bechberger.femtocli.processor.codegen;

import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.TypeSpec;
import me.bechberger.femtocli.processor.model.CommandModel;
import me.bechberger.femtocli.processor.model.OptionModel;
import me.bechberger.femtocli.processor.model.ParameterModel;

import javax.lang.model.element.Modifier;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Generates parser classes for FemtoCli commands.
 *
 * <p>For a command class named X, generates XParser class with:
 * <ul>
 *   <li>parse(String[] args) method that returns populated X instance</li>
 *   <li>Static helper methods for type conversion</li>
 *   <li>Help text generation</li>
 * </ul>
 */
public class ParserGenerator {


    public ParserGenerator() {
    }

    /**
     * Generates a parser class for the given command model.
     */
    public JavaFile generate(CommandModel model) {
        String parserClassName = model.getClassName() + "Parser";
        String packageName = model.getPackageName();

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(parserClassName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addJavadoc("Generated parser for $L command.\n", model.getName())
                .addJavadoc("\n<p>This class is auto-generated by FemtoCli annotation processor.</p>");

        boolean hasParameters = !model.getParameters().isEmpty();
        boolean hasOptions = !model.getAllOptions().isEmpty() || model.isMixinStandardHelpOptions();
        boolean hasMultiValue = model.getAllOptions().stream().anyMatch(OptionModel::hasSplit);
        boolean hasSubcommands = !model.getSubcommands().isEmpty() || !model.getMethodSubcommands().isEmpty();

        // Add fields for tracking options and positional arguments
        FieldTrackingGenerator.addOptionTrackingFields(classBuilder, hasParameters, hasOptions, hasMultiValue);

        // Add helper methods for type conversion
        addTypeConversionMethods(classBuilder, model);

        if (hasOptions) {
            // Add option name to field name map method
            OptionLookupGenerator.addOptionLookupMethods(model, classBuilder, hasMultiValue);
            OptionLookupGenerator.addTypeInfoMethods(model, classBuilder);

            // Add option value setter method
            OptionValueGenerator.addOptionValueMethod(model, classBuilder, hasMultiValue);
        }

        // Add parameter handling methods
        if (hasParameters) {
            ParameterHandlerGenerator parameterHandlerGenerator = new ParameterHandlerGenerator(model);
            parameterHandlerGenerator.addParameterHandlingMethods(classBuilder);
        }

        // Add subcommand routing if present
        if (hasSubcommands) {
            ParseMethodGenerator.addFindSubcommandMethod(model, classBuilder);
        }

        // Add the main parse implementation (parseRoot) - this does the actual parsing
        if (hasSubcommands) {
            ParseMethodGenerator.addParseRootMethod(model, classBuilder, hasParameters, hasOptions, hasMultiValue, hasSubcommands);
        }

        // Add the public parse() method that routes to subcommands if needed
        if (hasSubcommands) {
            // CommandParsingResult class is generated inside parseWithSubcommand
            ParseMethodGenerator.addParseWithSubcommandMethod(model, classBuilder);
        } else {
            ParseMethodGenerator.addParseSimpleMethod(model, classBuilder, hasParameters, hasOptions, hasMultiValue);
        }

        // Add help method
        HelpGenerator helpGenerator = new HelpGenerator(model);
        helpGenerator.addHelpMethod(classBuilder);

        TypeSpec parserClass = classBuilder.build();

        return JavaFile.builder(packageName, parserClass)
                .indent("  ")
                .build();
    }


    /**
     * Adds type conversion helper methods based on types used in the command.
     */
    private void addTypeConversionMethods(TypeSpec.Builder classBuilder, CommandModel model) {
        // Collect all unique field types from options and parameters
        Set<String> typeNames = new LinkedHashSet<>();
        for (OptionModel option : model.getAllOptions()) {
            typeNames.add(option.getFieldType().toString());
        }
        for (ParameterModel parameter : model.getParameters()) {
            typeNames.add(parameter.getFieldType().toString());
        }

        TypeConverterGenerator.addTypeConversionMethods(classBuilder, typeNames);
    }
}
